postgres:
  connection: "postgres://leaderboard:leaderboard@postgres:5432/leaderboard"
redis:
  addr: "redis:6379"
  pwd: "redis123"
  db: 1
is_redis_leaderboard_enabled: false
is_mv_leaderboard_enabled: false
